# Generated by Django 5.2.4 on 2025-08-13 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_post_publish_audit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exported_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("commit_sha", models.CharField(blank=True, max_length=64, null=True)),
                ("repo_url", models.URLField(blank=True, max_length=255, null=True)),
                ("branch", models.CharField(blank=True, max_length=64, null=True)),
                ("path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "export_status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed"), ("pending", "Pending")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("export_error", models.TextField(blank=True, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="export_jobs", to="blog.post"
                    ),
                ),
            ],
        ),
    ]
