# Generated by Django 5.2.4 on 2025-08-14 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_exportjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="post",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(fields=("site", "slug"), name="uniq_site_slug"),
        ),
    ]
