# Generated by Django 5.2.4 on 2025-08-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_alter_post_unique_together_alter_post_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="exported_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="post",
            name="last_exported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="posts", to="blog.category"),
        ),
    ]
