# Generated by Django 5.2.4 on 2025-08-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_post_exported_hash_post_last_exported_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="exported_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hash dell'export (contenuto/front matter) per rilevare cambiamenti lato Jekyll.",
                max_length=64,
                null=True,
            ),
        ),
    ]
