# Generated by Django 5.2.4 on 2025-08-01 11:51

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=blog.models.upload_to_post_image
            ),
        ),
    ]
