# Generated by Django 5.2.4 on 2025-08-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_postimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
