# Generated by Django 5.2.4 on 2025-08-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_alt_post_background_post_canonical_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="background",
            field=models.CharField(
                blank=True,
                default="https://res.cloudinary.com/dkoc4knvv/image/upload/v1/",
                help_text="Incolla qui l'URL Cloudinary dell'immagine di background. Es: https://res.cloudinary.com/dkoc4knvv/image/upload/v1/…",
                max_length=200,
            ),
        ),
    ]
