# Generated by Django 5.2.4 on 2025-08-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_category_site_slug_unique"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="category",
            new_name="blog_catego_site_id_69b4ec_idx",
            old_name="blog_category_site_slug_idx",
        ),
        migrations.AddField(
            model_name="post",
            name="export_status",
            field=models.CharField(
                choices=[("success", "Success"), ("failed", "Failed"), ("pending", "Pending")],
                default="pending",
                help_text="Stato export/build",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="last_pages_build_url",
            field=models.URLField(
                blank=True, help_text="URL build/errore ultima pubblicazione", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="media_strategy",
            field=models.CharField(
                choices=[("external", "External URLs (Cloudinary/S3)"), ("commit", "Commit assets in repo")],
                default="external",
                help_text="How to handle post images: external URLs or commit assets in repo.",
                max_length=20,
            ),
        ),
    ]
