# Generated by Django 5.2.4 on 2025-08-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_blog_category_site_slug_idx_blog_catego_site_id_69b4ec_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_export_path',
            field=models.CharField(blank=True, help_text='Percorso ultimo file esportato su Jekyll', max_length=255, null=True),
        ),
    ]
