# Generated by Copilot on 2025-08-15
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
