# Generated by Django 5.2.4 on 2025-08-15 23:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_add_created_at"),
    ]

    # No-op: campo già corretto in 0001_initial.
    operations = []
