# Generated by Django 5.2.4 on 2025-09-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_remove_post_seo_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="seo_title",
        ),
    ]
