"""Add last_published_hash to Post

Generated by agent to support idempotent publish.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_remove_post_seo_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="last_published_hash",
            field=models.CharField(max_length=64, blank=True, default="", help_text="Hash dell'ultimo contenuto pubblicato (front-matter + body)"),
        ),
    ]
