"""Add action and message fields to ExportJob

Generated by patch for Issue 6: unify ExportJob audit schema.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0023_add_index_last_published_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportjob",
            name="action",
            field=models.CharField(choices=[('publish','Publish'),('refresh','Refresh/Check'),('delete_db_only','Delete DB-only'),('delete_repo_and_db','Delete Repo + DB')], max_length=32, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="message",
            field=models.TextField(null=True, blank=True),
        ),
    ]
