# Generated by Django 5.2.4 on 2025-09-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_add_exportjob_action_message"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="post_last_pub_hash_idx",
        ),
        migrations.RemoveField(
            model_name="exportjob",
            name="export_error",
        ),
        migrations.AlterField(
            model_name="post",
            name="last_published_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Hash dell'ultimo contenuto pubblicato (front-matter + body)",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(db_collation="utf8mb4_unicode_ci", max_length=200),
        ),
    ]
