# Generated by Django 5.2.6 on 2025-09-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0025_remove_post_post_last_pub_hash_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
    ]
