# Generated by Django 5.2.6 on 2025-09-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0028_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
    ]
