# Generated by Django 5.2.6 on 2025-09-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0027_alter_post_slug"),
        ("blog", "0031_alter_post_slug"),
    ]

    operations = []
