# Generated by Django 5.2.6 on 2025-09-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0032_merge_0027_alter_post_slug_0031_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name="author",
            unique_together={("site", "slug")},
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["site", "slug"], name="blog_author_site_id_5d1f1f_idx"),
        ),
    ]
