# Generated by Django 5.2.6 on 2025-09-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0033_alter_author_slug_alter_author_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="author",
            name="blog_author_site_id_5d1f1f_idx",
        ),
        migrations.AlterUniqueTogether(
            name="author",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="author",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors",
                to="blog.site",
            ),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["slug"], name="blog_author_slug_5b1b82_idx"),
        ),
    ]
