# Generated by Django 5.2.6 on 2025-10-19 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0036_alter_category_slug_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["cluster_slug", "subcluster_slug"]},
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="post",
            name="repo_filename",
            field=models.CharField(
                blank=True,
                help_text="Percorso del file nel repo Jekyll (es. _posts/YYYY-MM-DD-slug.md)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PreviewSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("source_branch", models.CharField(help_text="Branch sorgente (es. main)", max_length=100)),
                ("preview_branch", models.CharField(help_text="Branch preview (es. preview/post-123)", max_length=100)),
                ("pr_number", models.IntegerField(blank=True, help_text="Numero della Pull Request GitHub", null=True)),
                ("preview_url", models.CharField(blank=True, help_text="URL dell'anteprima deployata", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pr_open", "PR Open"),
                            ("building", "Building"),
                            ("ready", "Ready"),
                            ("merged", "Merged"),
                            ("closed", "Closed"),
                            ("error", "Error"),
                        ],
                        default="created",
                        help_text="Stato corrente della preview",
                        max_length=20,
                    ),
                ),
                ("last_error", models.TextField(blank=True, help_text="Ultimo errore riscontrato", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        help_text="Site associato alla preview",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview_sessions",
                        to="blog.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["site", "status"], name="blog_previe_site_id_2c9509_idx"),
                    models.Index(fields=["pr_number"], name="blog_previe_pr_numb_662dcc_idx"),
                ],
            },
        ),
    ]
