# Generated by Django 5.2.6 on 2025-10-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0037_alter_category_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PreviewSession",
        ),
    ]
