# Generated by Django 5.2.6 on 2025-10-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0038_remove_preview_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="preview_url",
            field=models.URLField(
                blank=True,
                help_text="URL permanente della preview del post (es. https://owner.github.io/repo/preview/625/)",
                max_length=500,
                null=True,
            ),
        ),
    ]
