name: CI (Django)

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]

    env:
      DJANGO_SETTINGS_MODULE: blog_manager.settings
      SECRET_KEY: ci-not-secret
      DEBUG: "0"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install black isort flake8 pytest pytest-django

      - name: Lint (flake8)
        run: python -m flake8 blog_manager

      - name: Lint (isort)
        run: python -m isort --check-only --diff .

      - name: Lint (black)
        run: python -m black --check .

      - name: Django checks & migrate
        run: |
          python manage.py check
          python manage.py migrate --noinput

      - name: Run tests (pytest if available else Django test)
        run: |
          if [ -f pytest.ini ] || [ -f pyproject.toml ] && grep -q pytest pyproject.toml; then
            pytest -q
          else
            python manage.py test
          fi
