name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip
      - run: pip install black isort flake8
      # isort/black in modalità check ONLY, con stessi parametri della tua macchina
      - run: python -m isort . --check-only --profile black -l 120
      - run: python -m black . --check -l 120
      - run: python -m flake8 blog_manager

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    env:
      DJANGO_SETTINGS_MODULE: blog_manager.settings
      SECRET_KEY: ci-not-secret
      DEBUG: "0"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install pytest pytest-django
      - name: Django checks & migrate
        run: |
          python manage.py check
          python manage.py migrate --noinput
      - name: Run tests
        run: pytest -q
