name: PR CI & Artifacts (Django)

on:
  pull_request:
    branches: ['**']

permissions:
  contents: read

concurrency:
  group: pr-ci-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: blog_manager.settings.dev
      SECRET_KEY: ci-not-secret
      DEBUG: "0"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install pytest pytest-django coverage flake8 black isort

      - name: Lint
        run: |
          flake8 blog_manager scripts || true
          isort --check-only --diff . || true
          black --check . || true

      - name: Django checks & migrate (SQLite)
        run: |
          python manage.py check
          python manage.py migrate --noinput

      - name: Run tests with coverage
        run: |
          mkdir -p reports/coverage_html
          pytest -q \
            --junitxml=reports/junit.xml \
            --cov=blog_manager \
            --cov-report=xml:reports/coverage.xml \
            --cov-report=html:reports/coverage_html

      - name: Upload test reports (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: django-test-reports
          path: |
            reports/junit.xml
            reports/coverage.xml
            reports/coverage_html
          retention-days: 7

      # ---------- Opzionale: anteprima export Markdown ----------
      # Se hai (o aggiungi) uno script che salva i .md in una cartella,
      # questo blocco li carica come artifact "md-preview".
      - name: Export preview (dry-run)
        if: ${{ hashFiles('scripts/export_preview.py') != '' }}
        run: |
          mkdir -p artifacts/md-preview
          python scripts/export_preview.py --out-dir artifacts/md-preview --limit 10

      - name: Upload export preview (artifact)
        if: ${{ hashFiles('scripts/export_preview.py') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: md-preview
          path: artifacts/md-preview
          retention-days: 7